# Generated by Django 6.1.1 on 2026-09-18 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('memo', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name_raw', models.CharField(blank=True, default='', max_length=200)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('document_number', models.CharField(blank=True, default='', max_length=100)),
                ('file', models.FileField(upload_to='purchases/%Y/%m/')),
                ('status', models.CharField(choices=[('UPLOADED', '업로드됨'), ('PARSED', '파싱완료(검토대기)'), ('CONFIRMED', '확정'), ('FAILED', '파싱실패')], default='UPLOADED', max_length=20)),
                ('parse_error', models.TextField(blank=True, default='')),
                ('raw_llm_response', models.JSONField(blank=True, null=True)),
                ('llm_model', models.CharField(blank=True, default='', max_length=100)),
                ('supply_amount', models.BigIntegerField(default=0)),
                ('tax_amount', models.BigIntegerField(default=0)),
                ('total_amount', models.BigIntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-document_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('business_number', models.CharField(blank=True, default='', max_length=20)),
                ('memo', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=0)),
                ('raw_name', models.CharField(blank=True, default='', max_length=200)),
                ('spec', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_price', models.BigIntegerField(default=0)),
                ('amount', models.BigIntegerField(default=0)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='purchases.material')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchase')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='purchases.supplier'),
        ),
        migrations.CreateModel(
            name='MaterialAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='purchases.material')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_aliases', to='purchases.supplier')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('supplier', 'raw_name'), name='uniq_alias_supplier_rawname')],
            },
        ),
    ]
