# Generated by Django 6.1.1 on 2026-09-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_supplier_contact_and_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='supplier_draft',
        ),
    ]
