# Generated by Django 6.1.1 on 2026-09-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_remove_purchase_supplier_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='supplier_draft',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
