# Generated by Django 6.1.1 on 2026-10-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_purchase_supplier_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('UPLOADED', '업로드됨'), ('PARSING', '파싱중'), ('PARSED', '파싱완료(검토대기)'), ('CONFIRMED', '확정'), ('FAILED', '파싱실패')], default='UPLOADED', max_length=20),
        ),
    ]
