# Generated by Django 6.1.1 on 2026-09-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('TOSSPOS', '토스포스')], max_length=20)),
                ('webhook_id', models.CharField(db_index=True, max_length=100)),
                ('event_id', models.CharField(blank=True, max_length=100, null=True)),
                ('event_type', models.CharField(blank=True, default='', max_length=100)),
                ('payload', models.JSONField()),
                ('is_processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'webhook_id'), name='uniq_webhook_source_id')],
            },
        ),
    ]
