# Generated by Django 6.1.1 on 2026-09-13 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('MATEPOS', '매트포스'), ('TOSSPOS', '토스포스')], max_length=20)),
                ('store_code', models.CharField(db_index=True, max_length=50)),
                ('store_name', models.CharField(blank=True, default='', max_length=100)),
                ('order_seq', models.CharField(max_length=64)),
                ('business_date', models.DateField(blank=True, null=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('channel_order_no', models.CharField(blank=True, max_length=100, null=True)),
                ('order_category', models.CharField(blank=True, default='', max_length=20)),
                ('channel', models.CharField(blank=True, default='', max_length=50)),
                ('channel_detail', models.CharField(blank=True, default='', max_length=100)),
                ('order_type', models.CharField(blank=True, default='', max_length=20)),
                ('payment_status', models.CharField(choices=[('결제완료', '결제완료'), ('결제취소', '결제취소')], default='결제완료', max_length=20)),
                ('payment_method', models.CharField(blank=True, default='', max_length=50)),
                ('delivery_company', models.CharField(blank=True, max_length=50, null=True)),
                ('sale_amount', models.BigIntegerField(default=0)),
                ('discount_amount', models.BigIntegerField(default=0)),
                ('net_sale_amount', models.BigIntegerField(default=0)),
                ('channel_delivery_fee', models.BigIntegerField(default=0)),
                ('channel_discount', models.BigIntegerField(default=0)),
                ('actual_sale_amount', models.BigIntegerField(default=0)),
                ('taxable_amount', models.BigIntegerField(default=0)),
                ('vat', models.BigIntegerField(default=0)),
                ('non_taxable_amount', models.BigIntegerField(default=0)),
                ('cup_deposit', models.BigIntegerField(default=0)),
                ('online_delivery_fee', models.BigIntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('org_business_date', models.DateField(blank=True, null=True)),
                ('org_order_seq', models.CharField(blank=True, max_length=64, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-business_date', '-sold_at'],
                'indexes': [models.Index(fields=['business_date'], name='sales_sale_busines_89fc33_idx'), models.Index(fields=['source', 'store_code'], name='sales_sale_source_0d9818_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'store_code', 'order_seq'), name='uniq_sale_source_store_orderseq')],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_seq', models.IntegerField(default=0)),
                ('goods_cd', models.CharField(blank=True, default='', max_length=50)),
                ('goods_nm', models.CharField(blank=True, default='', max_length=200)),
                ('app_prc', models.BigIntegerField(default=0)),
                ('sale_qty', models.IntegerField(default=0)),
                ('sale_amt', models.BigIntegerField(default=0)),
                ('item_dc_amt', models.BigIntegerField(default=0)),
                ('taxable_amount', models.BigIntegerField(default=0)),
                ('vat', models.BigIntegerField(default=0)),
                ('non_taxable_amount', models.BigIntegerField(default=0)),
                ('sale_except_amt', models.BigIntegerField(default=0)),
                ('sale_except_yn', models.CharField(default='N', max_length=1)),
                ('packing_yn', models.CharField(default='N', max_length=1)),
                ('item_details', models.JSONField(blank=True, null=True)),
                ('item_opt_details', models.JSONField(blank=True, null=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
            options={
                'ordering': ['item_seq'],
            },
        ),
        migrations.CreateModel(
            name='SaleTender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_seq', models.IntegerField(default=0)),
                ('tender_cd', models.CharField(blank=True, default='', max_length=50)),
                ('tender_nm', models.CharField(blank=True, default='', max_length=50)),
                ('tender_amt', models.BigIntegerField(default=0)),
                ('change_amt', models.BigIntegerField(default=0)),
                ('pre_tender_yn', models.CharField(default='N', max_length=1)),
                ('return_yn', models.CharField(default='N', max_length=1)),
                ('approval_no', models.CharField(blank=True, max_length=50, null=True)),
                ('approval_dt', models.CharField(blank=True, max_length=20, null=True)),
                ('pur_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='sales.sale')),
            ],
            options={
                'ordering': ['tender_seq'],
            },
        ),
    ]
