# Generated by Django 6.1.1 on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sale",
            name="uniq_sale_source_store_orderseq",
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.UniqueConstraint(
                fields=("source", "store_code", "business_date", "order_seq"),
                name="uniq_sale_source_store_date_orderseq",
            ),
        ),
    ]
