# Generated by Django 6.1.1 on 2026-09-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_date_aware_order_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('진행중', '진행중'), ('결제완료', '결제완료'), ('결제취소', '결제취소')], default='결제완료', max_length=20),
        ),
    ]
