# Generated by Django 6.1.1 on 2026-10-08 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salecancel'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='salecancel',
            new_name='sales_salec_busines_4e15cd_idx',
            old_name='sales_salec_busines_idx',
        ),
        migrations.RenameIndex(
            model_name='salecancel',
            new_name='sales_salec_is_read_a7225d_idx',
            old_name='sales_salec_is_read_idx',
        ),
        migrations.RenameIndex(
            model_name='salecancel',
            new_name='sales_salec_source_8e2535_idx',
            old_name='sales_salec_source_idx',
        ),
    ]
